modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "${modIssueTracker}"
license = "${modLicense}"

[[mods]]
    modId = "smartcompletion"
    version = "${version}"
    displayName = "${modName}"
    authors = "${modAuthor}"
    description = "${modDescription}"
    logoFile = "icon.png"

[[dependencies.smartcompletion]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.smartcompletion]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"