modLoader = "javafml"
loaderVersion = "${neoForgeLoaderVersion}"
issueTrackerURL = "${modIssueTracker}"
license = "${modLicense}"

[[mods]]
    modId = "smartcompletion"
    version = "${version}"
    displayName = "${modName}"
    authors = "${modAuthor}"
    description = "${modDescription}"
    displayURL = "${modPage}"
    displayTest = "${modDisplayTest}"
    updateJSONURL = "${modUpdatesJSON}"
    logoFile = "icon.png"

[[dependencies.smartcompletion]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoForgeVersionRange}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.smartcompletion]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${neoForgeMinecraftVersion}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"
