plugins {
    id("net.neoforged.moddev")
}

val prop = rootProject.extra

val modId: String by rootProject
val modVersion: String by rootProject
val minecraftVersion: String by prop
val neoForgeVersion: String by project

val modProperties: Map<String, String> by prop


sourceSets.main {
    resources {
        // Include resources generated by data generators.
        srcDir("src/generated/resources")

        // Exclude common development only resources from finalized outputs
        exclude("**/*.bbmodel") // BlockBench project files
        exclude("src/generated/**/.cache") // datagen cache files
    }
}

neoForge {
    // Specify the version of NeoForge to use.
    version = neoForgeVersion

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        val client by creating {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        val server by creating {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        // // This run config launches GameTestServer and runs all registered gametests, then exits.
        // // By default, the server will crash when no gametests are provided.
        // // The gametest system is also enabled by default for other run configs under the /test command.
        // val gameTestServer by creating {
        //     type = "gameTestServer"
        //     systemProperty("neoforge.enabledGameTestNamespaces", modId)
        // }
        //
        // val data by creating {
        //     clientData()
        //
        //     // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
        //     // gameDirectory = project.file('run-data')
        //
        //     // Specify the examplemod for data generation, where to output the resulting resource, and where to look for existing resources.
        //     programArguments.addAll(
        //         "--mod", mod_id,
        //         "--all",
        //         "--output", file("src/generated/resources/").absolutePath,
        //         "--existing", file("src/main/resources/").absolutePath,
        //     )
        // }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // multi mod projects should define one per mod

        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

val commonImplementation by configurations.creating {
    isCanBeResolved = true
    isCanBeConsumed = false
    isTransitive = false
}

configurations {
    api.get().extendsFrom(commonImplementation)

    // Sets up a dependency configuration called 'localRuntime'.
    // This configuration should be used instead of 'runtimeOnly' to declare
    // a dependency that will be present for runtime testing but that is
    // "optional", meaning it will not be pulled by dependents of this mod.
    val localRuntime by creating {
        isCanBeResolved = true
        isCanBeConsumed = false
    }
    runtimeClasspath.get().extendsFrom(localRuntime)
}

dependencies {
    commonImplementation(project(":common")) {
        exclude("net.fabricmc")
    }

    // Example optional mod dependency with JEI
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    // compileOnly("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    // compileOnly("mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}")
    // We add the full version to localRuntime, not runtimeOnly, so that we do not publish a dependency on it
    // localRuntime("mezz.jei:jei-${mc_version}-neoforge:${jei_version}")

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation("blank:coolmod-${mc_version}:${coolmod_version}")

    // Example mod dependency using a file as dependency
    // implementation(files("libs/coolmod-${mc_version}-${coolmod_version}.jar"))

    // Example project dependency using a sister or child project:
    // implementation(project(":myproject"))

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

val copyCommonClasses by tasks.registering(Copy::class) {
    mustRunAfter(":common:compileJava")
    mustRunAfter(":common:compileTestJava")
    mustRunAfter(tasks.compileJava.get())

    from(project(":common").layout.buildDirectory.get().dir("classes"))
    into(project.layout.buildDirectory.dir("classes"))
}

val copyCommonResources by tasks.registering(Copy::class) {
    mustRunAfter(":common:processResources")
    mustRunAfter(":common:processTestResources")
    mustRunAfter(":common:compileTestJava")
    mustRunAfter(tasks.processResources.get())
    mustRunAfter(tasks.processTestResources.get())

    from(project(":common").layout.buildDirectory.dir("resources"))
    into(project.layout.buildDirectory.dir("resources"))
}

tasks.classes.configure {
    dependsOn(copyCommonClasses)
    dependsOn(copyCommonResources)
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    val modProperties = modProperties.toMap()

    inputs.properties(modProperties)

    // Exclude .dev folders from the mod resources
    exclude("**/.dev/**")

    expand(modProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

tasks.processResources {
    // Exclude .dev folders from the mod resources
    exclude("**/.dev/**")
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main {
    resources {
        srcDir(generateModMetadata)
    }
}

// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)


tasks.named<Jar>("jar") {
    val modId = modId
    inputs.property("projectName", modId)

    from(rootProject.projectDir.resolve("LICENSE")) {
        rename {
            "${it}_${modId}"
        }
    }
}

tasks.named<Test>("test") {
    // Re-enable if tests are added, otherwise JUnit fails the build
    enabled = false
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register<MavenPublication>("neoforge") {
            artifactId = "$modId-$minecraftVersion-${project.name}"
            version = modVersion

            from(components["java"])
        }
    }
    repositories {
        maven {
            url = project.projectDir.toURI().resolve("repo")
        }
    }
}
