# Java
javaVersion = 21

# Minecraft
minecraftVersion = 1.20.6
neoForgeMinecraftVersion = [1.20.5,)
fabricMinecraftVersion = >=1.20.3
fabricCompatibleMinecraftVersions = 1.20.3, 1.20.4, 1.20.5, 1.20.6
neoForgeCompatibleMinecraftVersions = 1.20.5, 1.20.6

# Architectury
architecturyVersion = 12.1.3
parchmentVersion=

# Fabric
fabricLoaderVersion = 0.16.0
fabricApiVersion = 0.100.4+1.20.6

# Forge
neoForgeVersion = 20.6.119
neoForgeVersionRange = [20.5,)
neoForgeLoaderVersion = [1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile = neoforge.mods.1.20.6.toml