# Java
javaVersion=21

# Minecraft
minecraftVersion=1.21.7
neoForgeMinecraftVersion=[1.21.7,)
fabricMinecraftVersion=>=1.21.7
fabricCompatibleMinecraftVersions=1.21.7
neoForgeCompatibleMinecraftVersions=1.21.7

# Architectury
architecturyVersion=16.1.4
parchmentVersion=

# Fabric
fabricLoaderVersion=0.16.14
fabricApiVersion=0.128.2+1.21.7

# Forge
neoForgeVersion=21.7.11-beta
neoForgeVersionRange=[21.7.0-beta,)
neoForgeLoaderVersion=[1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile=neoforge.mods.1.20.6.toml