# Java
javaVersion=21

# Minecraft
minecraftVersion=1.21.3
neoForgeMinecraftVersion=[1.21.2,)
fabricMinecraftVersion=>=1.21.2
fabricCompatibleMinecraftVersions=1.21.2, 1.21.3
neoForgeCompatibleMinecraftVersions=1.21.2, 1.21.3

# Architectury
architecturyVersion=14.0.4
parchmentVersion=

# Fabric
fabricLoaderVersion=0.16.0
fabricApiVersion=0.106.1+1.21.3

# Forge
neoForgeVersion=21.3.58
neoForgeVersionRange=[21.2,)
neoForgeLoaderVersion=[1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile=neoforge.mods.1.20.6.toml