# Java
javaVersion=21

# Minecraft
minecraftVersion=1.21.6
neoForgeMinecraftVersion=[1.21.6,)
fabricMinecraftVersion=>=1.21.6
fabricCompatibleMinecraftVersions=1.21.6
neoForgeCompatibleMinecraftVersions=1.21.6

# Architectury
architecturyVersion=16.1.4
parchmentVersion=

# Fabric
fabricLoaderVersion=0.16.14
fabricApiVersion=0.128.2+1.21.6

# Forge
neoForgeVersion=21.6.0-beta
neoForgeVersionRange=[21.6.0-beta,)
neoForgeLoaderVersion=[1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile=neoforge.mods.1.20.6.toml