# Java
javaVersion=21

# Minecraft
minecraftVersion=1.21.4
neoForgeMinecraftVersion=[1.21.4,)
fabricMinecraftVersion=>=1.21.4
fabricCompatibleMinecraftVersions=1.21.4
neoForgeCompatibleMinecraftVersions=1.21.4

# Architectury
architecturyVersion=15.0.1
parchmentVersion=

# Fabric
fabricLoaderVersion=0.16.0
fabricApiVersion=0.110.5+1.21.4

# Forge
neoForgeVersion=21.4.23-beta
neoForgeVersionRange=[21.4,)
neoForgeLoaderVersion=[1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile=neoforge.mods.1.20.6.toml