# Java
javaVersion=21

# Minecraft
minecraftVersion=1.21.9
neoForgeMinecraftVersion=[1.21.9,)
fabricMinecraftVersion=>=1.21.9
fabricCompatibleMinecraftVersions=1.21.9, 1.21.10
neoForgeCompatibleMinecraftVersions=1.21.9, 1.21.10

# Architectury
architecturyVersion=18.0.5
parchmentVersion=

# Fabric
fabricLoaderVersion=0.17.2
fabricApiVersion=0.134.0+1.21.9

# Forge
neoForgeVersion=21.9.16-beta
neoForgeVersionRange=[21.9.0-beta,)
neoForgeLoaderVersion=[1.0,)
## Used to select the [neoforge.]mods.<version>.toml file to copy into the jar
modsTomlFile=neoforge.mods.1.20.6.toml