## Java
javaVersion=25

## Minecraft
# See latest versions here:
#   https://projects.neoforged.net/neoforged/neoforge
#   https://fabricmc.net/develop
minecraftVersion=26.1.2
fabricCompatibleMinecraftVersion=>=26.1
fabricCompatibleMinecraftVersions=26.1,26.1.1,26.1.2
neoForgeCompatibleMinecraftVersion=[26.1,)
neoForgeCompatibleMinecraftVersions=26.1,26.1.1,26.1.2

## Fabric
loomVersion=1.16-SNAPSHOT
fabricLoaderVersion=0.19.2
fabricApiVersion=0.149.1+26.1.2

## NeoForge Properties
modDevGradleVersion=2.0.141
neoForgeVersion=26.1.2.65-beta
neoForgeCompatibleLoaderVersion=[1.0,)
