## Java
javaVersion=25

## Minecraft
# See latest versions here:
#   https://projects.neoforged.net/neoforged/neoforge
#   https://fabricmc.net/develop
minecraftVersion=26.2
fabricCompatibleMinecraftVersion=>=26.2
fabricCompatibleMinecraftVersions=26.2,26.2,26.2
neoForgeCompatibleMinecraftVersion=[26.2,)
neoForgeCompatibleMinecraftVersions=26.2

## Fabric
loomVersion=1.17-SNAPSHOT
fabricLoaderVersion=0.19.3
fabricApiVersion=0.155.2+26.2

## NeoForge Properties
modDevGradleVersion=2.0.141
neoForgeVersion=26.2.0.25-beta
neoForgeCompatibleLoaderVersion=[1.0,)
