## Java
javaVersion=25

## Minecraft
# See latest versions here:
#   https://projects.neoforged.net/neoforged/neoforge
#   https://fabricmc.net/develop
minecraftVersion=26.3
fabricCompatibleMinecraftVersion=>=26.3
fabricCompatibleMinecraftVersions=26.3
neoForgeCompatibleMinecraftVersion=[26.3,)
neoForgeCompatibleMinecraftVersions=26.3

## Fabric
loomVersion=1.17-SNAPSHOT
fabricLoaderVersion=0.19.3
fabricApiVersion=0.161.0+26.3

## NeoForge Properties
modDevGradleVersion=2.0.148
neoForgeVersion=26.3.0.11-beta
neoForgeCompatibleLoaderVersion=[1.0,)
neoForgeModsTomlTemplate=26.3
